name: 'Deploy'
run-name: 'Deploy'
permissions: {}

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy'
    uses: teddybeermaniac/GitHub.Workflows/.github/workflows/caprover-deploy-image.yml@master
    with:
      image: rancher/hello-world:v0.1.2
      application: '${{ vars.CAPROVER_APPLICATION }}'
    secrets:
      host: '${{ secrets.CAPROVER_HOST }}'
      token: '${{ secrets.CAPROVER_TOKEN }}'
