name: Build
run-name: Build
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - develop
      - master

    tags:
      - '*'

  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: 'Build ${{ github.repository }}'
    uses: teddybeermaniac/GitHub.Workflows/.github/workflows/docker-build-image.yml@master
    with:
      # context: .
      # file:
      authors: 'John Doe <john.doe@example.com>'
      # platforms: amd64,arm64
      # image_name:
