name: Deploy
run-name: Deploy
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy ${{ github.repository }}'
    uses: teddybeermaniac/GitHub.Workflows/.github/workflows/caprover-deploy-dockerfile.yml@master
    with:
      # context: .
      # file:
      # platforms: amd64
      application: '${{ vars.CAPROVER_APPLICATION }}'
      authors: 'John Doe <john.doe@example.com>'
    secrets:
      host: '${{ secrets.CAPROVER_HOST }}'
      token: '${{ secrets.CAPROVER_TOKEN }}'
      # header_name: '${{ secrets.CAPROVER_HEADER_NAME }}'
      # header_value: '${{ secrets.CAPROVER_HEADER_VALUE }}'
