# Builds a Dockerfile, pushes the image to ghcr.io, and deploys it to the specified CapRover instance.
name: 'CapRover deploy Dockerfile'
permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      context:
        description: 'Path to Docker context (default: .)'
        type: string
        required: false
        default: .

      file:
        description: 'Path to Dockerfile (default: {context}/Dockerfile)'
        type: string
        required: false

      platforms:
        description: 'Platforms to build image for (default: amd64)'
        type: string
        required: false
        default: amd64

      authors:
        description: 'Author contact information'
        type: string
        required: true

      application:
        description: 'Application name'
        type: string
        required: true

    secrets:
      host:
        description: 'CapRover instance URL'
        required: true

      token:
        description: 'Application token'
        required: true

      header_name:
        description: 'Additional header name'
        required: false

      header_value:
        description: 'Additional header value'
        required: false

jobs:
  build:
    name: Build
    uses: ./.github/workflows/docker-build-image.yml
    with:
      context: '${{ inputs.context }}'
      file: '${{ inputs.file }}'
      platforms: '${{ inputs.platforms }}'
      authors: '${{ inputs.authors }}'

  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/caprover-deploy-image.yml
    with:
      image: '${{ needs.build.outputs.image }}'
      application: '${{ inputs.application }}'
    secrets:
      host: '${{ secrets.host }}'
      token: '${{ secrets.token }}'
      header_name: '${{ secrets.header_name }}'
      header_value: '${{ secrets.header_value }}'
