# Deploys a Docker image to the specified CapRover instance.
name: 'CapRover deploy image'
permissions: {}

on:
  workflow_call:
    inputs:
      image:
        description: 'Image to deploy'
        type: string
        required: true

      application:
        description: 'Application name'
        type: string
        required: true

    secrets:
      host:
        description: 'URL to CapRover instance'
        required: true

      token:
        description: 'Application token'
        required: true

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: 'Deploy ${{ inputs.image }} image as ${{ inputs.application }} application to CapRover'
        uses: docker://caprover/cli-caprover:2.2.3
        env:
          CAPROVER_APP: '${{ inputs.application }}'
          CAPROVER_APP_TOKEN: '${{ secrets.token }}'
          CAPROVER_IMAGE_NAME: '${{ inputs.image }}'
          CAPROVER_URL: '${{ secrets.host }}'
        with:
          args: 'caprover deploy'
