# Builds a Dockerfile and pushes the image to ghcr.io.
name: 'Docker build image'
permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      context:
        description: 'Path to Docker context (default: .)'
        type: string
        required: false
        default: .

      authors:
        description: 'Author contact information to be embedded in labels'
        type: string
        required: true

      platforms:
        description: 'Platforms to build the image for (default: amd64,arm64)'
        type: string
        required: false
        default: amd64,arm64

      image_name:
        description: 'Image name (default: lowercase repository name)'
        type: string
        required: false

    outputs:
      image:
        value: '${{ jobs.build.outputs.image }}'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    outputs:
      image: '${{ fromJSON(steps.metadata.outputs.json).tags[0] }}'

    steps:
      - name: 'Set IMAGE_URL environment variable'
        run: |
          if [[ -z "${INPUT_IMAGE_NAME}" ]]; then
            IMAGE_NAME="${GITHUB_REPOSITORY#*/}"
          else
            IMAGE_NAME="${INPUT_IMAGE_NAME}"
          fi
          IMAGE_URL="ghcr.io/${GITHUB_REPOSITORY_OWNER}/${IMAGE_NAME}"

          printf 'IMAGE_URL=%s\n' "${IMAGE_URL}" >> "${GITHUB_ENV}"
        env:
          INPUT_IMAGE_NAME: '${{ inputs.image_name }}'

      - name: 'Populate Docker metadata'
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: '${{ env.IMAGE_URL }}'
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.authors=${{ inputs.authors }}
            org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{ major }}.{{ minor }}.{{ patch }},prefix=v,priority=9999
            type=semver,pattern={{ major }}.{{ minor }},prefix=v,priority=9998
            type=semver,pattern={{ major }},prefix=v,priority=9997
            type=sha,prefix=,priority=9996
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }},priority=9995
            type=raw,value=edge,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }},priority=9994

      - name: 'Set IMAGE_NAME environment variable'
        run: |
          IMAGE_NAME="${IMAGE_TAG/:*/}"

          printf 'IMAGE_NAME=%s\n' "${IMAGE_NAME}" >> "${GITHUB_ENV}"
        env:
          IMAGE_TAG: '${{ fromJSON(steps.metadata.outputs.json).tags[0] }}'

      - name: 'Checkout ${{ inputs.repository }} repository'
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 'Login to ghcr.io'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ github.token }}'

      - name: 'Setup Buildx'
        uses: docker/setup-buildx-action@v2
        with:
          platforms: '${{ inputs.platforms }}'

      - name: 'Set up QEMU for ${{ inputs.platforms }} platforms'
        if: '${{ inputs.platforms != ''amd64'' }}'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: '${{ inputs.platforms }}'

      - name: 'Build ${{ github.event_name != ''pull_request'' && ''and push '' || '''' }}${{ env.IMAGE_NAME }} image'
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: '${{ inputs.context }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          outputs: 'type=image,name=target,annotation-index.org.opencontainers.image.description=${{ fromJSON(steps.metadata.outputs.json).labels[''org.opencontainers.image.description''] }},push=${{ github.event_name != ''pull_request'' }}'
          platforms: '${{ inputs.platforms }}'
          tags: '${{ steps.metadata.outputs.tags }}'
